### ISSUE TITLE
Generation of import cycles

### ISSUE THREAD

**Issue by thehgregor** [palantir/conjure-go#112] opened 2020-04-08 17:31 UTC
## What happened?

If an API definition has cyclic package references, the code generated by Conjure Go won't build:
- MyService uses InfoType in package my.api
- InfoType references InfoSubType in package my.api.subpackage
- InfoSubType references InfoEnum in package my.api

Please note that the API definition is not under our control. It is corresponding to an existing system written in a language that supports cyclic references (Java, I assume).

Compiling the generated code fails with:
```
import cycle not allowed
package ./src/myprogram
	imports sample/my/api/service
	imports sample/my/api
	imports sample/my/api/subpackage
	imports sample/my/api

```

Full API definition:
```
{
    "version": 1,
    "errors": [],
    "types": [
        {
            "type": "object",
            "object": {
                "typeName": {
                    "name": "InfoType",
                    "package": "my.api"
                },
                "fields": [
                    {
                        "fieldName": "someField",
                        "type": {
                            "type": "reference",
                            "reference": {
                                "name": "InfoSubType",
                                "package": "my.api.subpackage"
                            }
                        },
                        "docs": "Some detailed information.\n"
                    }
                ],
                "docs": "Some information.\n"
            }
        },
        {
            "type": "object",
            "object": {
                "typeName": {
                    "name": "InfoSubType",
                    "package": "my.api.subpackage"
                },
                "fields": [
                    {
                        "fieldName": "someSubField",
                        "type": {
                            "type": "reference",
                            "reference": {
                                "name": "InfoEnum",
                                "package": "my.api"
                            }
                        },
                        "docs": "Make your choice.\n"
                    }
                ],
                "docs": "Some detailed information.\n"
            }
        },
        {
            "type": "enum",
            "enum": {
                "typeName": {
                    "name": "InfoEnum",
                    "package": "my.api"
                },
                "values": [
                    {
                        "value": "GOOD",
                        "docs": null
                    },
                    {
                        "value": "BAD",
                        "docs": null
                    }
                ],
                "docs": "Either good or bad.\n"
            }
        }
    ],
    "services": [
        {
            "serviceName": {
                "name": "MyService",
                "package": "my.api.service"
            },
            "endpoints": [
                {
                    "endpointName": "getInfo",
                    "httpMethod": "GET",
                    "httpPath": "/info",
                    "auth": {
                        "type": "header",
                        "header": {}
                    },
                    "args": [],
                    "returns": {
                        "type": "reference",
                        "reference": {
                            "name": "InfoType",
                            "package": "my.api"
                        }
                    },
                    "docs": "Some information.\n",
                    "deprecated": null,
                    "markers": []
                }
            ],
            "docs": "Returns information.\n"
        }
    ]
}
```

## What did you want to happen?

Conjure Go should at least detect such an issue and fail. But what we would actually need is that it generates extra packages that transform the import cycles into a linear structure (in the above example generate separate packages for InfoType and InfoEnum).

**Comment by nmiyake** [comment] 2020-04-08 17:37
Yes, unfortunately this is a known issue -- there's discussion about whether this should be handled at the Conjure-level at https://github.com/palantir/conjure/issues/131.

It is possible to do the extra package generation to work around this issue, but that has its downsides as well. Specifically, it means that the package for a generated definition can change if a cyclical import is introduced -- a file that was part of package `a.b.c` can change to be `a.b.c.other` just by virtue of a different definition changing to introduce a cycle. The only way to prevent this a priori would be to generate every type in its own package, which is also not nice from a usability perspective.

Open to brainstorming solutions here, but just wanted to flag these things first.

**Comment by thehgregor** [comment] 2020-04-08 22:57
Thanks for the quick reaction on this! I put my point of view into the discussion that you have mentioned. I still think the proposed way is the best one, all by trying to limit the negative impacts this has.

**Comment by nmiyake** [comment] 2020-04-08 23:04
Thanks! Agree that making output package name unique on conflict is likely the best way forward for now, and is of decent importance since it's currently not possible for `conjure-go` to generate code for definitions that are currently considered valid.

Will treat this as a priority for this repo, but can't commit to a specific timeline at this point. If this is blocking something urgent, please let me know so we can prioritize accordingly.

**Comment by thehgregor** [comment] 2020-04-10 15:58
Perfect, thank you. It won't be a blocking issue for us for the next two weeks. But it will become a problem for us later on as most of the API definitions that we will consume have this kind of circular dependencies.

**Comment by nmiyake** [comment] 2023-01-19 00:38
This is becoming more important to handle, so noting current thoughts.

There are 2 main challenges here:

1. As long as Conjure itself permits circular references (https://github.com/palantir/conjure/issues/131), there will always exist valid definitions for which Go _cannot_ generate code if the "package" field is used as specified. Trivial example:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.apollo.deployment.api.v2.objects.v1
        fields:
          objectTwo: ObjectTwo
      ObjectTwo:
        package: com.palantir.apollo.deployment.api.v2.objects.v2
        fields:
          objectOne: ObjectOne
```

The only way to generate code that matches this definition in Go is to generate both objects in the same package. This can be done, but there would also need to be extra logic to deal with name collisions -- in the example above, if `ObjectTwo` was defined in a separate file as `Object1` and imported, then there would be a cycle, and generating both objects in the same package would result in a name collision. It is possible to track this and do an automatic disambiguation, but this would add extra logic and also make the resulting code less readable/usable.

2. Cycles can be introduced any time a definition is updated, and in order to generate compatible generated code it is almost always necessary to change at least one package into which code is generated. This means that compile errors can be introduced by updating a definition.

For example, assume we start with the definition:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.apollo.deployment.api.v2.objects.v1
        fields:
          name: string
          objectTwo: ObjectTwo
      ObjectTwo:
        package: com.palantir.apollo.deployment.api.v2.objects.v2
        fields:
          name: string
```

When the generation is run, `v1.ObjectOne` and `v2.ObjectTwo` are written out and used throughout the codebase.

At a later time, the definition is updated to introduce a cycle:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.apollo.deployment.api.v2.objects.v1
        fields:
          name: string
          objectTwo: ObjectTwo
      ObjectTwo:
        package: com.palantir.apollo.deployment.api.v2.objects.v2
        fields:
          name: string
          objectOne: ObjectOne
```

Now, assume that this is worked around by generating both `ObjectOne` and `ObjectTwo` into the `v1` package, so that there is `v1.ObjectOne` and `v1.ObjectTwo`.

The generated code now compiles/works, but all previous references to `v2.ObjectTwo` in the codebase will be broken, and need to be changed back.

The only way to preemptively/deterministically avoid this is to write all generated code into the same package, but this would cause a large pain in terms of usability/readability and code organization.

**Comment by nmiyake** [comment] 2023-01-19 00:55
Another aspect here is that, although determining whether or not an import cycle exists is fairly easy, figuring out the manner in which to resolve it is not necessarily as straightforward. There are often situations like A -> B -> C -> A, where an object in A references an object in B references an object in C references a type definition in A. In such a scenario, the most effective manual solution is often to move the type in A to a new package A', such that we have A -> B-> C-> A', and possibly A -> A' for any references in A that now use A'.

However, as noted in the previous comment, there are certain cycles where generating to a new package will not work, and the only solution is to generate into the same package.

As such, coming up with a generic approach that solves all possible cases in an effective way is a difficult problem (and even if a solution is possible, the generated code is still likely to be less than ideal because it will be hard to reason about why it was generated the way it was and may cause compile breaks compared to previously generated code).

**Comment by nmiyake** [comment] 2023-01-27 20:00
Update: based on discussion in core Conjure issue in https://github.com/palantir/conjure/issues/131#issuecomment-1398747661, we've determined that we won't block package reference cycles at the Conjure definition level, and have verified that, based on the current constraints, at the extreme this can always be worked around by generating into a single namespace (Go package).

At the highest level, here are the broad approaches:
1. Always generate code in a way that guarantees correctness and stability
    1. Basic approach would be to generate all code into a single Go package and ensure there are no name conflicts for types (see appendix for example)
2. Default to generating code in a way that cycles *could* occur, but change generated code if cycles are introduced
3. Add heuristics to code generation that lowers probability of cycles occurring (but does not guarantee it)
    1. For example, generating different types (aliases vs. objects etc.) in different sub-packages will eliminate the class of cycles that occur when an external package referenced by an object refers back to an alias type in the same package — however, this approach cannot eliminate cycles, as it’s possible to have cycles just between objects via fields etc.
4. Add ability to configure generator to modify the generated output in a way that allows users to work around cycles in a definition
    1. For example, allow Conjure configuration to allow users to specify that specific Conjure types should be mapped to specific Go packages

It is also possible to combine some of the approaches above, but I believe that these above encompasses most of the practical solutions.

These approaches have the following general pros/cons:

1. Always generate code in a way that guarantees correctness and stability
    1. Pros: Guarantees stability of generated code and correctness
    2. Cons: Major downside to usability and readability of generated code
2. Default to generating code in a way that cycles *could* occur, but change generated code if cycles are introduced
    1. Pros: In majority of cases where definition does not have a cycle, maintains current output
    2. Cons: The generated code between different versions of the same definition can cause compilation breaks if the updated definition introduces a cycle
3. Add heuristics to code generation that lowers probability of cycles occurring (but does not guarantee it)
    1. Pros: may reduce the universe of definitions which cause an issue with cycles
    2. Cons: would likely break existing generated code from a compile perspective, and is not sufficient as a solution on its own for definitions where the heuristic doesn’t resolve a cycle
4. Add ability to configure generator to modify the generated output in a way that allows users to work around cycles in a definition
    1. Pros: In majority of cases where definition does not have a cycle, maintains current output, provides flexibility for solution
    2. Cons: Puts burden of resolving cycles on API consumer rather than producer, and requires all impacted consumers to duplicate effort to resolve (or share solution/approach out-of-band)

My gut feeling is that approach 1 is too disruptive/costly relative to the actual problem and that approach 4 is not a path we want to take since it burdens consumers and would likely lead to duplicated work. Approach 3 is pretty pragmatic and may be a good first step to buy time, but ultimately is not sufficient on its own.

This means that, as an actual solution, approach 2 is likely what we would want to take.

I have outlined each approach and the tradeoffs involved in detail below. Feedback on either the high-level approach or specifics on any of the approaches below would be appreciated.


# Always generate code in a way that guarantees correctness and stability

## 1. Generate all types into single package and use "package + name" as the type name
This approach is the most extreme, but also has the most stability and specific guarantees.

In this design, all of the code generated for a particular Conjure IR would be written into the same package, and the type names would be "{Package}_{Name}", where all instances of "." in "{Package}" are replaced with "_".

Pros:
* Guaranteed that there will not be any cycles in generated code
* Generated code is stable (will not change/introduce compile breaks with IR change unless the IR itself introduces breaks)
* It is easy figure out the generator input (package and name) based on looking at the output
* Implementation is simple

Cons:
* Type names would be very cumbersome/hard to read and use in code — `objects.DeclaredConfigOverrides` would become `deploymentstate.Com_Palantir_Apollo_Deployment_API_v2_Objects_DeclaredConfigOverrides`
* More minor, but browsing generated code may also be harder (less hierarchical organization)

Initial evaluation:
* Although this is the most straightforward from a mechanical point of view, the user experience downside is likely too great to justify it (especially when the problem it solves does not impact a majority of the consumed definitions)

## 2. Approach 1, but use heuristics to make types more readable by humans
This approach would be to use approach 1 in principle, but to attempt to apply heuristics to make the output more readable/usable. For example:

* Start by generating all types without the package qualifier
* IF there are any conflicts (type name is the same but package names differ), then disambiguate by adding package components as needed, but just for those types

New cons:
* Generated output is no longer guaranteed to be stable across versions
    * In particular, if a type that differs only in package name is introduced in a later version, then the generated IR before and after that version will differ for the same type (which will cause a generated code compile break for a non-breaking IR change)
        * For example, if v1.0.0 of an API defines a type “foo.Bar” and that generates as “Bar”, but in v1.1.0 the API adds “bar.Bar”, then the generated code for v1.1.0 will have “foo_Bar” and “bar_Bar”, and code that compiled against v1.0.0 using just “Bar” will now break

## 3. Use approach 1, but also generate types into the current package-path package and use a type definition that references the generated type
As an example, for a Conjure definition that defines `com.palantir.apollo.foo.Foo` and `com.palantir.apollo.bar.Bar`, it would generate `output.Apollo_Foo_Foo` and `output.Apollo_Bar_Bar` in the `output` package, but would also generate `output/apollo/foo.Foo` with definition `type Foo output.Apollo_Foo_Foo` and `output/apollo/bar.Bar` with definition `type Bar output.Apollo_Bar_bar`.

Pros:
* Guaranteed that there will not be any cycles in generated code
* Generated code is stable (will not change/introduce compile breaks with IR change unless the IR itself introduces breaks)
* Generated aliases allow for developers to reference types using those aliases in a fairly ergonomic/readable way

Cons:
* Struct fields, map types, service arguments etc. would all use unaliased types, so users would need to perform type conversions in many places
* May be confusing to have generated code

# Default to generating code in a way that cycles *could* occur, but change generated code if cycles are introduced
This approach is a more pragmatic one that reflects the reality that, in practice, most Conjure definitions probably do not have any package cycles. In this implementation, the generator will check to see if there are any package cycles before performing generation. If there are not, then it will generate the Conjure code in the same manner that it does today.

However, if it does detect a package cycle, then the generator will generate code in a way that does not cause an import cycle in Go. One option is to fall back to one of the methods outlined above that guarantees that cycles will never occur, but this still has the drawbacks listed above.

The other approach would be to use a process/algorithm that attempts to resolve cycles in the generated code by changing generated packages for specific types, and to try to do so in a manner that minimizes the number of packages moved/changed.

In either of these approaches, one drawback is that the location for generated code for an existing type may change due to a non-breaking Conjure change. For example, if version 1.1.0 of a Conjure definition defines type A in package “foo” and type B in package “bar” version 1.2.0 of the definition adds fields that cause a cycle between type “A” and “B”, then the generated code for 1.2.0 will have to move at least one of these types to a different package, which will cause existing valid code to have a compile break (but not a wire break).

## Creating the package/type import graph
The following formalizes how cycles are determined:
* For a given type or service, its package is the value of “package” in Conjure
* A type or service is said to reference a type (there is no way to semantically reference a service in Conjure) if that type occurs anywhere within the definition of the type or service
* Because all types and services have a package, the type reference graph can be converted to a package reference graph
* Generated Go code will have a cycle if any cycle exists in the package reference graph
    * A specialized case of a cyclic package reference graph is a cyclic type reference graph

## Algorithm for resolving cycles
The goals for resolving cycles are the following:
* The output should be deterministic for a given input
* The algorithm should be able to always resolve all cycles for a given input
* The algorithm should try to be the least disruptive possible in terms of breaks it introduces for existing code and usability of generated code
    * Specifically, it should try to move as few types as possible and keep names as close to defined as possible

The following is a proposal for an algorithm that attempts to do this. I believe it makes sense logically, but have not fully vetted it (I have not proved that it meets all of the properties above). Would appreciate any feedback — absent that, my proposal would be to implement it and then verify its behavior/validity on various constructed test cases for cyclical definitions.

* For each Conjure package (ordered by name) and for each type in that package (in struct order and in order of the list):
    * Generate the type/package reference graph for the type
        * If there are 1 or more cycles in the graph, resolve each of them
    * For package reference cycles that are type reference cycles:
        * Every type in the chain of references must be generated in the same package to resolve the cycle
        * Identify the first package in the cycle and create a new package with the same path/name under a prefix package
            * Default prefix package name is “conjurego”, but crawl package graph first and if there is any package that has this string as the first portion, add an integer to the end that will make the generated name unique (“conjurego1”, etc.)
            * For example, if original package was generated in “product/api/objects/v2”, new package would be at “conjurego/product/api/objects/v2”
            * Update in-memory Conjure definition such that every type in the cycle has the new package instead of the original one
    * For package reference cycles that are not type reference cycles:
        * Need to move all types in the same package referenced from anywhere outside the package to separate packages
        * Generate the “conjurego” top-level package and move types to that package as required
* Once the above is done, check if there are still any cycles and, if so, repeat the process until there are no more cycles

## Examples of Cycles

### Cyclical type
Object types defined in different packages that have each other as fields causes a type cycle:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.apollo.deployment.api.v2.objects.v1
        fields:
          objectTwo: ObjectTwo
      ObjectTwo:
        package: com.palantir.apollo.deployment.api.v2.objects.v2
        fields:
          objectOne: ObjectOne
```

The only resolution is to generate both types in the same package.

### Cyclical package without cyclical type
Package cycle that is not a type cycle: a type in one package references a type in another package and that type references a different type in the original package.

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.apollo.deployment.api.v2.objects.v1
        fields:
          objectTwo: ObjectTwo
      MySimpleAlias:
        package: com.palantir.apollo.deployment.api.v2.objects.v1
        alias: string
      ObjectTwo:
        package: com.palantir.apollo.deployment.api.v2.objects.v2
        fields:
          aliasField: MySimpleAlias
```

There are a few possible resolutions:
* Move the “MySimpleAlias” type to a new separate package
* Move “ObjectOne” or “ObjectTwo” to the same package

### Package graph that has multiple different cycles
* To fill out

### Package graph that has a cycle where cyclic package is not the leaf node
* To fill out

Maybe formalize solution algorithm to state that, if a cycle is discovered in a subgraph, algorithm should just be applied on subgraph where cycle node is the start node?

# Add heuristics to code generation that lowers probability of cycles occurring (but does not guarantee it)
This approach is more of a complimentary approach — it would not be sufficient on its own, but if we proceed with a solution that falls back to resolving cycles, we could modify the way in which code is generated to reduce the probability of them occurring.

One of the common cases we’ve observed with cycles is one where a cycle is introduced due to objects and aliases being defined in the same package. Here is a simplified example definition:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.deployment.api.v2.objects.v1
        fields:
          objectTwo: ObjectTwo
      MySimpleAlias:
        package: com.palantir.deployment.api.v2.objects.v1
        alias: string
      ObjectTwo:
        package: com.palantir.deployment.api.v2.objects.v2
        fields:
          aliasField: MySimpleAlias
```

In this case, the reference ObjectOne -> ObjectTwo -> MySimpleAlias creates a package cycle because ObjectOne and MySimpleAlias are both generated in the same package.

This class of cycle could be eliminated by generating the Go types for different types in their own packages. For example, if we always prefaced the package path with the generated object types, in the above example we would generate:
* objects.deployment.api.v2.objects.v1
    * ObjectOne
* aliases.deployment.api.v2.objects.v1
    * MySimpleAlias
* objects.deployment.api.v2.objects.v2
    * ObjectTwo

In this case, the Go package import graph would be objects…v1 -> objects…v2 -> aliases…v1, and thus there would not be an import cycle.

This heuristic cannot eliminate cycles entirely, but may cut down on their manifestation in practice.

There is also a question of whether we should move all generation to use heuristics such as this (in which case it will introduce a compile break to all Conjure generated code on upgrade), or whether it should be used as a fallback mechanism after cycles are detected.

## Approach 1: always prefix package path with type being generated
In this proposal, the Go package path for a type would be prefixed with the name of the general type being created. For example, all objects would use “objects”, aliases would use “aliases”, etc. So, for an alias and object defined in the conjure package “com.palantir.foo”, the generated Go packages would be:
* objects.foo
* aliases.foo

The reason for using a prefix rather than suffix is to make the rest of the package path reflect the usual path and to keep the naming consistent.

Although this approach would reduce the likelihood of cycles caused by other types in the same package, it does not eliminate it. For example, if we had:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.deployment.api.v1
        fields:
          aliasField: MySimpleAlias
      MySimpleAlias:
        package: com.palantir.deployment.api.v2
        alias: string
      MySimpleAliasTwo:
        package: com.palantir.deployment.api.v2
        alias: ObjectOne
```

Then with the proposed approach here we would still have objects…v1.ObjectOne -> aliases…v2.MySimpleAlias, but would also have aliases…v2.MySimpleAliasTwo -> objects…v1.ObjectOne, which would still cause a Go package cycle.

Segmenting generated types in this manner would also increase the use of import statements — Go code that imports multiple different types from a single Conjure package would end up importing multiple different Go packages with the same name, which would require named imports/disambiguation in code.

## Approach 2: prefix generated packages in a manner in which every type is in its own package
This approach is similar to approach 1, but takes it a step further by ensuring that every generated type is in its own package. This eliminates the class of cycles that occur due to other sibling types in the same package. In this approach, the package prefix would be “{Type}.{TypeName}.{PackagePath}.

For example, for:

```
types:
  definitions:
    objects:
      ObjectOne:
        package: com.palantir.deployment.api.v1
        fields:
          aliasField: MySimpleAlias
      MySimpleAlias:
        package: com.palantir.deployment.api.v2
        alias: string
      MySimpleAliasTwo:
        package: com.palantir.deployment.api.v2
        alias: ObjectOne
```

This would generate:

* objects.objectone.deployment.api.v1.ObjectOne
* aliases.mysimplealias.deployment.api.v2.MySimpleAlias
* aliases.mysimplealiastwo.deployment.api.v2.MySimpleAliasTwo

The main disadvantage of this scheme is that it eliminates the class of cycles caused by “sibling” types in the same package. However, it would greatly increase the number of packages (since it would create a package per type rather than a package per package or package-typeclass) and would necessitate many named imports and disambiguation in consuming code.

# Add ability to configure generator to modify the generated output in a way that allows users to work around cycles in a definition
An implementation of this approach would be something like the following:

* By default, Conjure generates code in the same way that it does today
* Expose configuration for conjure-go that allows the user to specify overrides that control the Go package into which specific Conjure types are generated
    * For example, the configuration could be something like “com.palantir.foo.v1.Bar: foo.v1.custom”, which would specify that the Go package for the “Bar” type in the Conjure “com.palantir.foo.v1” package should be generated into the Go package path “foo.v1.otherbar” (rather than the default “foo.v1”).

Exposing this configuration knob would allow end users to control the generated code and resolve any cycles manually by controlling the Go package created for output.

The downside to this approach is that it shifts the burden of dealing with a problem introduced by the definition to the consumer. If a definition creates a cycle, every consumer of that generation will generate invalid code, and this approach would require them to all debug/fix it themselves. Although there could be work put towards ad-hoc/out-of-band ways to share common workarounds/configuration for definitions that are known to cause cycles, it’s a very inefficient approach that duplicates a lot of effort.

**Closed as completed** 2023-03-20 22:53 UTC
